name: ygg-torrent-mcp

services:
  ygg-torrent-mcp:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    image: ygg-torrent-mcp
    container_name: ygg-torrent-mcp
    ports:
      - 8765:8000
    env_file:
      - ../.env
    networks:
      - mcp-servers

networks:
  mcp-servers:
    name: mcp-servers
    driver: bridge